In [1]:
import numpy as np

In [2]:
print(np)

<module 'numpy' from 'C:\\Users\\13kau\\AppData\\Roaming\\Python\\Python38\\site-packages\\numpy\\__init__.py'>


In [3]:
nparr = np.array([1,2,3,4,5])

In [4]:
print(type(nparr))

<class 'numpy.ndarray'>


In [5]:
print(type(nparr),"--->",nparr.ndim,"-->",nparr)

<class 'numpy.ndarray'> ---> 1 --> [1 2 3 4 5]


In [6]:
nparr = np.array([[1,2,3,4,5],[2,4,6,8,10]])

In [7]:
print(type(nparr),"--->",nparr.ndim,"-->",nparr)

<class 'numpy.ndarray'> ---> 2 --> [[ 1  2  3  4  5]
 [ 2  4  6  8 10]]


In [8]:
#1D NumPy Array ---> [1,2,3,4]
#2D NumPy Array ---> [[1,2,3,4]]
#3D NumPy Array ---> [[[1,2,3,4]],[[1,2,3,4]]]

In [9]:
narr2 = np.array([1,2,3,'a',5]) #if there is 1 string present then all are converted into string
print(narr2) #homogenious

['1' '2' '3' 'a' '5']


In [10]:
narr3 = np.array([1,2,3,'',5])
print(narr3)

['1' '2' '3' '' '5']


In [11]:
na1 = np.array([1,2,3,'a',5])
na2 = np.array([1,2,3,4,5])
na3 = np.array([1,23,4,5])
print(na1.dtype)
print(na2.dtype)
print(na3.dtype) #types of numpy

<U11
int32
int32


In [12]:
# automatic creating numpy array
# arr0= np.linspace(0,5)
# print(arr0)
# arr1 = np.linspace(0,5,10) #np.linspace(start,end, num,endpoint, retstep, dtype
# print(arr1)
# arr2 =p.linspace(0,5,10,retstep=True)
# print(arr2)
arr4=np.linspace(0,5,10,endpoint=False, retstep=True)
print(arr4)

(array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]), 0.5)


In [13]:
#logspace --> if we want number in logarithms
#logspace(start, stop, num, endpoint, base,dtype)
larr1 = np.logspace(1,20,10)
print(larr1)

[1.00000000e+01 1.29154967e+03 1.66810054e+05 2.15443469e+07
 2.78255940e+09 3.59381366e+11 4.64158883e+13 5.99484250e+15
 7.74263683e+17 1.00000000e+20]


In [14]:
#range in numpy
# arange(start, stop ,step)
ral = np.arange(0,10,2)
print(ral)

[0 2 4 6 8]


In [15]:
# true or false in 0, 1
zero = np.zeros((2,3))
print(zero)
ones = np.ones((3,5))
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
random = np.random.rand(3,2)
print(random)

[[0.33068179 0.37276138]
 [0.49530406 0.44791371]
 [0.91124809 0.0015075 ]]


In [17]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [18]:
# why numpy? ---> Time!
#differenciate 
import timeit

size = 1000
iternations = 1000

narr = np.array(range(10000))

list1 = list(range(size))
print(type(list1), "--->",len(list1))

def sumlist(lst1):
    return sum(lst1)
print(type(narr), "--->",len(narr))

def sumarraynp(lst2):
    return np.sum(lst2)

resuttime = timeit.timeit('sumlist(list1)',globals=globals() ,number=iternations)
print("time-->",resuttime)


resuttime1 = timeit.timeit('sumarraynp(narr)',globals=globals() ,number=iternations)
print("np.time-->",resuttime1)

<class 'list'> ---> 1000
<class 'numpy.ndarray'> ---> 10000
time--> 0.011523700000000137
np.time--> 0.013949999999999907


In [20]:
#therefore more time in numpy
# numpy has c advantage

In [21]:
#measure size
import sys
size = 1000
list2 = list(range(1000))
print("type:-->", type(list2))
narr2 = np.array(range(1000))
print("type:-->", type(narr2))

print("size of list", sys.getsizeof(1)*len(list2))
print("sixe of numpy", narr2.itemsize*len(narr2))

type:--> <class 'list'>
type:--> <class 'numpy.ndarray'>
size of list 28000
sixe of numpy 4000


# Shape

In [27]:
array1 = np.array([(1,2,3,4),(5,6,7,8)])
print(array1)
print(array1.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [30]:
array2 = np.array([(1,2,3,4),(5,6,7,8)])
print(f"old ---> {array2}")
print(array1.shape)
a = array1.reshape(4,2)
print(f"old ---> {a}")

old ---> [[1 2 3 4]
 [5 6 7 8]]
(2, 4)
old ---> [[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Slizing

In [32]:
array3 = np.array([(1,2,3,4),(5,6,7,8)])
print(f"value in 3rd position is --> {array3[0,3]}")

value in 3rd position is --> 4


In [34]:
array4 = np.array([(1,2,3,4),(5,6,7,8)])
print(f"value in 3rd position startng from 0th arary is --> {array4[0:,3]}")

value in 3rd position startng from 0th arary is --> [4 8]


In [36]:
array5 = np.array([(1,2,3,4),(5,6,7,8)])
print(array5.max())#maximum and minimum number
print(array5.min())

8
1


In [37]:
array6 = np.array([(1,2,3,4),(5,6,7,8)])
print(array6.sum())

36


In [39]:
#Axis1 ---> Sum of Vertical Rows
#Axis0 ---> Sum of columns
array7 = np.array([(1,2,3,4),(5,6,7,8)])
print(f"sum of columns --> {array7.sum(axis=0)}")
print(f"sum of rows -->{array7.sum(axis=1)}")

sum of columns --> [ 6  8 10 12]
sum of rows -->[10 26]


In [40]:
#standard deviation and squareoot
array8 = np.array([(1,2,3,4),(5,6,7,8)])
print(np.sqrt(array8))

[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]]


In [41]:
array9 = np.array([(1,2,3,4),(5,6,7,8)])
print(np.std(array9))

2.29128784747792


In [57]:
#vstack and hstack
array11 = np.array([(1,2,3,4),(5,6,7,8)])
array12 = np.array([(1,2,3,4),(5,6,7,8)])

print(f"vstack is ---> {np.vstack((array11,array12))}")
print(f"vstack is ---> {np.hstack((array11,array12))}")

# addition of two array
print(f"sum of 2 array is ---> {array11+array12}")

#ravel --> maing 2d to 1d
a = array11.ravel()
print(f"the reval is --> {a}")
print(a.ndim)

vstack is ---> [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
vstack is ---> [[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]
sum of 2 array is ---> [[ 2  4  6  8]
 [10 12 14 16]]
the reval is --> [1 2 3 4 5 6 7 8]
1
